config/routes.rb
PhotoBlog::Application.routes.draw do

  get "pages/about"
  get "pages/contact"

  resources :users do
    collection do
      match "/activate/:token" => "users#activate", :as => "activate"
    end

    resources :posts do
      member do
        put "publish"
        put "unpublish"
      end
      resources :images, :only => [:destroy]
    end
  end

  scope "/blog" do
    match "/:slug" => "posts#display", :as => :profile_view, :via => :get
    match "/:slug/posts/:id" => "posts#show", :as => :profile_view_post, :via => :get
  end

  resource :user_session, :controller => :user_session do
  end

  match "login" => "user_session#login", :as => :login, :via => :get
  match "logout" => "user_session#destroy", :as => :logout, :via => :delete
  match "/pushed" => "application#pushed", :via => :post

  root :to => "user_session#login"

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
    find_by_login_method  :find_by_activated_user
end

app/controllers/user_session_controller.rb
class UserSessionController < ApplicationController
  before_filter :check_logged_in?, :only => [:login]

  def login
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_to user_url(current_user)
    else
      generate_flash_message
      render "login"
    end
  end

  def destroy
    @user_session = UserSession.find

    if @user_session.destroy
      redirect_to root_url
    else
      flash[:error] = "Woops looks like something went wrong. We're on it."
      redirect_to root_url
    end
  end

  private
  def generate_flash_message
    user = User.where(:email => params[:user_session][:email]).first
    if user && !user.active?
      flash[:error] = "Please activate your account by clicking on the link emailed to you."
    else
      flash.now[:error] =  "Username or password is invalid."
    end
  end


end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/views/user_session/login.html.erb
<div id="block">
  <%#= render :partial => "layouts/error_display", :locals => {:resource => @user_session, :main_error_msg => "Please fix these errors to proceed"} %>
  <div class="standard-block">
    <%= form_for :user_session, @user_session, :url => user_session_url, :html => {:method => :post, :class => "form"} do |f| %>

        <div class="group">
          <label class="label"> Email </label>
          <%= f.text_field :email, :class => "text_field" %>
        </div>

        <div class="group">
          <label class="label"> Password </label>
          <%= f.password_field :password, :class => "text_field" %>
        </div>

        <div class="group">
          <%= f.submit "Login", :class => "button" %>
          <p> <%= link_to "Sign up", new_user_url, :class =>"link" %> <br/>
              <%= link_to "Forgot Password?", "", :class => "link" %>
          </p>

        </div>
    <% end %>
  </div>
</div>

app/views/user_session/logout.html.erb
<h1>UserSession#logout</h1>
<p>Find me in app/views/user_session/logout.html.erb</p>