config/routes.rb
PhotoBlog::Application.routes.draw do

  get "pages/about"
  get "pages/contact"

  resources :users do
    collection do
      match "/activate/:token" => "users#activate", :as => "activate"
    end

    resources :posts do
      member do
        put "publish"
        put "unpublish"
      end
      resources :images, :only => [:destroy]
    end
  end

  scope "/blog" do
    match "/:slug" => "posts#display", :as => :profile_view, :via => :get
    match "/:slug/posts/:id" => "posts#show", :as => :profile_view_post, :via => :get
  end

  resource :user_session, :controller => :user_session do
  end

  match "login" => "user_session#login", :as => :login, :via => :get
  match "logout" => "user_session#destroy", :as => :logout, :via => :delete
  match "/pushed" => "application#pushed", :via => :post

  root :to => "user_session#login"

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :images, :dependent => :destroy

  accepts_nested_attributes_for :images

  validates :title, :presence => true
  validates :images, :presence => true

  def publish!
    self.update_attributes(:published => true)
  end

  def unpublish!
    self.update_attributes(:published => false)
  end

  def last_image?
    (self.images.length == 1)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :request_login, :except => [:display, :index]
  before_filter :fetch_user, :except => [:display, :show]
  before_filter :fetch_post, :only => [ :edit, :update, :destroy, :publish, :unpublish]

  def new
    @post = @user.posts.new
    0.upto(4) do
      @post.images.build
    end
  end

  def create
    @post = @user.posts.build(params[:post])

    if @post.save
      flash[:notice] = "Your post has been successfully saved."
      redirect_to user_posts_url(@user)
    else
      0.upto(4) do
        @post.images.build
      end
      render "new"
    end
  end

  def show
     @post = @user.posts.find(params[:id])
  end

  def edit
    0.upto(4 - @post.images.size) do
      @post.images.build
    end
  end

  def update
    if @post.update_attributes(params[:post])
      flash[:notice] = "Your post has been successfully updated."
      redirect_to user_posts_url(@user)
    else
      0.upto(4 - @post.images.size) do
        @post.images.build
      end
      render "edit"
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = "Your post has been successfully deleted."
    end

    redirect_to user_posts_url(@user)
  end

  def index
    @posts = @user.posts.order("created_at DESC")
  end

  def publish
    if !@post.published? && photo_set_owner?(@post)
      flash[:notice]="Your post has been successfully published"
      @post.publish!
    end

      redirect_to user_posts_url(@user)
  end

  def unpublish
    if @post.published? && photo_set_owner?(@post)
      flash[:notice] = "Your post has been successfully unpublished"
      @post.unpublish!
    end

    redirect_to user_posts_url(@user)
  end

  def display
    @user = User.where(:slug => params[:slug]).includes(:profile).first

    if @user
      @posts = @user.posts.order("created_at DESC").limit(5)
      render :template => "posts/index"
    else
      render_404
    end
  end

  private

  def fetch_post
    @post = @user.posts.find(params[:id])
  end

  def fetch_user
    @user = User.find(params[:user_id])
    rescue ActiveRecord::RecordNotFound => e
    render_404 unless @user
  end
 end

app/helpers/posts_helper.rb
module PostsHelper
  def posts_home?
    (controller_name == 'posts' && (action_name == 'index' || action_name == 'display'))
  end
end

app/views/posts/_display_photos.html.erb
<% post.images.each_with_index do  |img, index| %>
    <% if index == 0 || !posts_home?%>
        <%= image_tag img.photo(:large), :width => "900", :class => "image post post-#{post.id} image-#{index} shadow" %>
    <% else %>
        <%= image_tag img.photo(:large), :width => "900", :class => "image post post-#{post.id} image-#{index} hidden shadow" %>
    <% end %>
<% end %>

app/views/posts/_each_post.html.erb
<div id='photo-set'>

  <div id='photo-description' class='round'>
    <div id="manage-links">
      <%= link_to "Hide Text", "#", :class => 'hide-text' %>
      <% if photo_set_owner?(post) %>
          | <%= link_to "Delete", user_post_url(@user, post), :method => :delete, :confirm =>"Are you sure you want to delete this post? There is no undo?" %> |
          <%= link_to "Edit", edit_user_post_url(@user,post) %> |
          <% unless post.published? %>
              <%= link_to "Publish", publish_user_post_url(@user, post), :method => :put %>
          <% else %>
              <%= link_to "Unpublish", unpublish_user_post_url(@user, post),:method => :put %>
          <% end %>
      <% end %>
    </div>
    <div class="clear"></div>

    <div id='photo-title' class='hideable'>
      <h3>
        <%= link_to post.title, user_post_url(@user, post), :class => 'h3-link' %>
      </h3>
    </div>
    <div id='photo-body' class='hideable'>
      <% if posts_home?  %>
          <%= truncate(post.description, :length => 500, :omission => "...") %>
      <% else %>
          <%= post.description %>
      <% end  %>
    </div>
    <div id='photo-timestamp' class='hideable'> <em>-<%= post.created_at.strftime("%d %B %Y") %></em></div>
  </div>


  <% if posts_home? %>
      <div id='photo-navigator'>
        <%  post.images.each_with_index do |img, index|%>
            <%= link_to "o", "#", :class => "photo-nav post-#{post.id} image-#{index}"   %>
        <% end %>
      </div>
  <% end %>

  <div id='photo'>
    <%= render :partial => "display_photos", :locals => {:post => post} %>
  </div>

  <div class='clear'></div>
</div>

app/views/posts/_form.html.erb
<div class="group">
  <label class="label"> Title </label>
  <%= f.text_field :title, :class => "text_field" %>
</div>

<div class="group">
  <label class="label"> Description </label>
  <%= f.text_area :description, :size => "4x10", :class => "text_area" %>
</div>

<div class="group">

  <%= f.fields_for :images do |img| %>
      <% if img.object.new_record? %>
          <%= render :partial => "posts/image_fields", :locals => {:builder => img} %>
      <% end %>
  <% end %>


  <%#= post_add_image_fields "Add another photo", f, :images %>


</div>

<style>


    .add-more-link{
        text-decoration:underline;
        font-weight:normal;
        font-size:12px;
        color:#CCC;

    }
</style>

app/views/posts/_image_fields.html.erb
<%= builder.file_field :photo, :class => 'new-image' %>

app/views/posts/_title.html.erb
<% content_for :title do %>
    <%= link_to @user.profile.blog_name, profile_view_url(@user.slug), :class => "link" %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= render :partial => "title" %>

<div id="block">
  <%= render :partial => "layouts/error_display", :locals => {:resource => @post, :main_error_msg => "Please fix these errors to proceed"} %>
  <div class="standard-block">
    <%= form_for :post, @post, :url => user_post_url(@user), :html => {:method => :put, :class => "form", :multipart => true} do |f| %>

        <% @post.images.each do |image| %>
            <% unless image.new_record? %>
                <%= image_tag image.photo(:medium), :width => "460", :class => "image" %>
                <div id='image-options'>
                  <%= link_to "[ Remove ]", user_post_image_url(@user, @post, image), :method => :delete, :confirm => "Are you sure you want to delete this image from the photoset?" %>
                </div>
                <div class="clear"></div>
            <% end %>
        <% end %>

        <%= render :partial => "form", :locals => {:f => f} %>

        <div class="group">
          <%= f.submit "Update", :class => "button" %>
          <button>
            <%= link_to "Cancel", user_posts_url, :class => "button"%>
          </button>
        </div>
    <% end %>
  </div>
</div>

<style>

    #image-options{
        float:right;
        width:60px;

    }
    #image-options a{
        font-size:11px;
        color:#fff;
        text-decoration:none;
    }

    #image-options a:hover{
        color:#eee;
        text-decoration:underline;
    }

    .button{
        text-decoration:none;
        color:#000;
    }
</style>

app/views/posts/index.html.erb
<%= render :partial => "title" %>

<div class='image-set post-display'>
  <% @posts.each do |post| %>
      <%= render :partial => "each_post", :locals =>{:post => post } %>
  <% end %>

</div>

app/views/posts/new.html.erb
<%= render :partial => "title" %>

<div id="block">
  <%= render :partial => "layouts/error_display", :locals => {:resource => @post, :main_error_msg => "Please fix these errors to proceed"} %>
  <div class="standard-block">
    <%= form_for :post, @post, :url => user_posts_url, :html => {:method => :post, :class => "form", :multipart => true} do |f| %>

      <%= render :partial => "form", :locals => {:f => f} %>

        <div class="group end-of-the-line">
          <%= f.submit "Post", :class => "button" %>
        </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for :title do %>
    <%= link_to @user.profile.blog_name, profile_view_url(@user.slug), :class => "link" %>
<% end %>


<p>
  <%= link_to "Back to posts", user_posts_url(@user), :class => "link" %>
</p>

<%= render :partial => "each_post", :locals => {:post => @post} %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>