config/routes.rb
PhotoBlog::Application.routes.draw do

  get "pages/about"
  get "pages/contact"

  resources :users do
    collection do
      match "/activate/:token" => "users#activate", :as => "activate"
    end

    resources :posts do
      member do
        put "publish"
        put "unpublish"
      end
      resources :images, :only => [:destroy]
    end
  end

  scope "/blog" do
    match "/:slug" => "posts#display", :as => :profile_view, :via => :get
    match "/:slug/posts/:id" => "posts#show", :as => :profile_view_post, :via => :get
  end

  resource :user_session, :controller => :user_session do
  end

  match "login" => "user_session#login", :as => :login, :via => :get
  match "logout" => "user_session#destroy", :as => :logout, :via => :delete
  match "/pushed" => "application#pushed", :via => :post

  root :to => "user_session#login"

end

app/views/layouts/_error_display.html.erb
<div class='error-display'>
  <% if resource.errors.any? %>
      <div  class='error-list translucent'>
        <ul>
          <p><strong> <%= main_error_msg  if main_error_msg.present? %> </strong></p>
          <% resource.errors.full_messages.each do |message|  %>
              <li> <%= message %> </li>
          <% end %>
        </ul>
      </div>
  <% end %>
</div>

<style>
  .error-display{
      margin-top:2em;
  }
    .error-list{
        background: none repeat scroll 0 0 #9A111A;
        border: 2px solid #CE0000;
        color: white;
        margin: 10px 0 20px;
        padding: 10px 20px;
        text-shadow: none !important;
    }

    .error-list ul li{
        list-style-type: disc;
        margin-left: 20px;

    }
</style>

app/views/layouts/_flash_messages.html.erb
<div id="flash-messages">
  <% if flash[:notice] %>
      <div class="flash-message">
        <%= flash[:notice] %>
      </div>
  <% end %>

  <% if flash[:error] %>
      <div class="flash-error">
        <%= flash[:error] %>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoBlog</title>
  <%= stylesheet_link_tag 'application','themes/default/default',  'themes/pascal/pascal', 'themes/orman/orman', 'nivo-slider' %>
  <%= javascript_include_tag "jquery", "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js", "jquery.nivo.slider.pack", "rails", "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="container">
  <div id="header">
    <div id="blog-title">
      <% unless current_user %>
        Pixxit <span style="font-family:chalkduster; font-size:12px; font-style:italic; color:maroon"> - Tell your story</span>
      <% else %>
        <%= yield :title %> |
        <%= link_to "Home", user_posts_url(current_user), :class =>'link' %>
      <% end  %>

    </div>
    <div id="primary-nav">
      <% if current_user %>
          <%= link_to "New post", new_user_post_url(current_user), :class => "link" %> |
          <%= link_to "Profile", "#", :class => "link" %> |
          <%= link_to "Logout", user_session_url, :method => :delete, :class => "link" %>
      <% else %>
          <%= link_to "Login", login_url%>
      <% end %>
    </div>
  </div>
  <div id="content">
    <div id="left">
      <%= render :partial => "layouts/flash_messages" %>
      <%= yield %>
    </div>
    <div id="right">
      <%= yield :right %>
    </div>
  </div>
  <div id="footer"></div>
</div>
</body>
</html>